### PR TITLE
update python setup

### PR DESCRIPTION
**Pull request by gboeing**

### CODE REVIEW

**Comment by gboeing** [comment]
@richardbeare I updated the python setup instructions in this PR

**Comment by richardbeare** [comment]
@gboeing @GNtem2 - Thanh will test, but I suspect we may need some screen shots to avoid confusion over which command window to use - e.g. the anaconda one vs windows default, and how to use cd in a command prompt. Occasional users of command line tools often get tripped up at the early stages and we don't want the reviewers to have problems.

**Comment by GNtem2** [comment]
@gboeing: Thanks Geoff. It works. I ran the new installation instructions as well as the Python Catchment down to geocoding. I would suggest a couple of edit to the instructions. For the novice should we change the instruction on directory eg
'C:\\Users\\Computer Name\\Documents\\DirectoryLocation\\2016 Census GCP All Geographies for VIC\\POA\\VIC\\2016Census_G01_VIC_POA.csv
where Computer Name is the name of your computer
and Directory Location is the path to the downloaded file
@richardbeare : We also need to put the path for files to be downloaded in this web document.
1-Download census and boundary data: list web address
2-Load census and boundary data

**Comment by gboeing** [comment]
> I suspect we may need some screen shots to avoid confusion over which command window to use - e.g. the anaconda one vs windows default, and how to use cd in a command prompt.

@richardbeare I clarify which prompt to use in f992833 and I'll provide some screenshots momentarily.

> I would suggest a couple of edit to the instructions. For the novice should we change the instruction on directory eg
'C:\Users\Computer Name\Documents\DirectoryLocation\2016 Census GCP All Geographies for VIC\POA\VIC\2016Census_G01_VIC_POA.csv
where Computer Name is the name of your computer
and Directory Location is the path to the downloaded file

@GNtem2 this would vary so drastically from machine to machine that I'd be hesitant to be so specific. For example, those instructions would not work on my machine as my folder structure does not include a `c:\Users\[computer_name]` path, nor do my downloads go to such a folder (thus, if I were a total novice, I'd be really confused when those detailed instructions didn't align with my own computer's setup at all). For generalizability's sake, I'll provide screenshots to show how to change directories, but I think we need to have users ascertain the absolute paths of their own downloaded files/folders.

**Comment by gboeing** [comment]
@richardbeare screenshots added in 3d7016a

**Comment by richardbeare** [comment]
@GNtem2 @gboeing We've included the ABS data in the repository. I suspect we need to be clearer on how we expect people to work with what we've provided - i.e. are they cutting and pasting from the web pages (which will be more difficult) or are they cloning the repository and loading files into rstudio/jupyter notebooks and running. If they are using a downloaded repo then they don't need to fetch a new copy of the ABS data.

**Comment by GNtem2** [comment]
@gboeing @richardbeare : is it possible to have both. I think most clinicians have never heard of GitHub and would not quite know. I think if you have the additional link then they won't complain that cut and paste does not work.
with regard to directory issue. I wonder if we can just write Your Directory Path to this file etc. Just assume that we clinicians are troglodytes.
I will write in the answer to the reviewers that we have tested the instructions and they work. Thanks very much Geoff for helping out novice python

**Comment by GNtem2** [comment]
@gboeing @richardbeare I found one issue which may be a problem for novice.
#in my version postcode boundaries column1=POA_CODE16 not POA_CODE
#postcode boundaries file do not contain POA as prefix to postcode eg 3000
#postcode demographics file contains POA as prefix to postcode eg POA3000
#so match cannot occur for joint operation

**Comment by richardbeare** [comment]
@gboeing A newbie query - where does environments.yml get used, or is it created by the installation process. I notice that it has changed, but doesn't appear to get used by the install process.

**Comment by gboeing** [comment]
@richardbeare it doesn't get used anywhere. I just create that file manually at the end of the environment creation process to document the complete final state. I always find it helpful if I want to go back and double check package versions, etc.

**Comment by richardbeare** [comment]
OK Thanks - so requirements.txt does everything?

**Comment by gboeing** [comment]
Correct: that's the only file we need to execute the instructions. environment.yml just documents the final results of executing those instructions.

**Comment by GNtem2** [comment]
@gboeing @richardbeare Success!!! Finally. I was about to give up today. I have updated the Frontiers response. The Python installation bits are a bit tricky compared to R. I have installed and reinstalled the packages several times (inexperience).

**Pull request merged**
